services:
  notificacao_php:
    container_name: notificacao_php
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    ports:
      - "9001:9000" # fpm
      - "5173:5173" # vite
    volumes:
      - "./.:/var/www/html"

  notificacao_http:
    container_name: notificacao_http
    image: nginx
    ports:
      - "8185:80" # http
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.docker/nginx/http.conf:/etc/nginx/conf.d/default.conf"
      - "./.:/var/www/html"
    depends_on:
      - "notificacao_php"

  notificacao_mysql:
    container_name: notificacao_mysql
    image: mysql
    ports:
      - "3306:3306" # mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Promo@2506"
    depends_on:
      - "notificacao_php"
